version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rms
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rms?schema=public
      JWT_SECRET: dev_secret
      CORS_ORIGINS: '*'
    depends_on:
    - db
    ports:
    - 4000:4000
  web:
    build:
      context: apps/web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: https://rms-cargotrack-pro2-production.up.railway.app:4000
      NEXT_PUBLIC_MAPBOX_TOKEN: ''
    depends_on:
    - api
    ports:
    - 3000:3000
volumes:
  pgdata: {}
